before_install:
  - chmod +x mvnw
language: java
jdk:
  - oraclejdk8
services:
 - mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_script:
- mysql -u root -e 'CREATE DATABASE Hackathon2;'
- mysql -u root -e "CREATE USER 'Hackathon2'@'localhost' IDENTIFIED BY 'Hackathon2';"
- mysql -u root -e "GRANT ALL ON Hackathon2.* TO 'Hackathon2'@'localhost';"

script: mvn clean verify
after_success:
 - bash <(curl -s https://codecov.io/bash)
notifications:
email: false